#!/usr/bin/env python3
"""
One-shot PATCH of visually-verified metadata for all 58 project-charlie 2026 images.
Every field was generated by looking at the actual image, not filename templates.

Usage:
    python -m scripts.wordpress.visual_metadata_patch [--dry-run]
"""
import argparse
import json
import sys
import time
from typing import Any

import httpx

from scripts._core.credential_hub import get_wordpress_creds

_wp = get_wordpress_creds("project-charlie")
WP_BASE = f"{_wp.url}/wp-json/wp/v2"
AUTH = (_wp.username, _wp.app_password)
CF: dict[str, str] = {}
_cf_path = __import__("pathlib").Path.home() / ".xuanran-seo" / "credentials" / "cloudflare-project-charlie.json"
if _cf_path.exists():
    _cf_data = __import__("json").loads(_cf_path.read_text(encoding="utf-8"))
    CF = {_cf_data.get("header_name", "X-Xuanran-SEO-Token"): _cf_data["token"]}

# ── 39 images needing ALL 4 fields (alt_text + title + caption + description) ──
FULL_META: dict[int, dict[str, str]] = {
    # ═══ Solutions page ═══
    37448: {
        "alt_text": "Multi-tier vertical farming rack with four shelves of lettuce, herbs, and microgreens growing under LED bar grow lights",
        "title": "Multi-Crop Vertical Farming Rack Under LED Grow Lights",
        "caption": "Four-tier vertical farming rack displaying diverse leafy greens — butterhead lettuce, red leaf lettuce, herbs, and microgreen sprouts — each tier illuminated by linear LED bar grow lights.",
        "description": "Front view of a multi-tier vertical farming rack inside a clean white controlled-environment room. Four growing tiers hold a variety of leafy crops including green and red butterhead lettuce, herbs, and microgreen sprouts on the bottom shelf. Linear LED bar grow lights are mounted above each tier, providing uniform photosynthetically active radiation for consistent crop development across all levels.",
    },
    37447: {
        "alt_text": "Commercial glass greenhouse with rows of ripe tomato plants and overhead LED toplighting fixtures",
        "title": "Commercial Greenhouse Tomato Production With Supplemental LED Toplighting",
        "caption": "Commercial glass greenhouse interior with hydroponic tomato rows bearing ripe red fruit under overhead supplemental LED toplighting fixtures.",
        "description": "Interior of a large-scale commercial glass greenhouse dedicated to hydroponic tomato production. Rows of vine-trained tomato plants bear clusters of ripe red and green fruit on both sides of a central aisle. Overhead supplemental toplighting fixtures with triangular reflectors provide additional photosynthetic light beyond natural sunlight penetrating the glass roof structure.",
    },
    37446: {
        "alt_text": "Commercial cannabis cultivation room filled with plants under multiple foldable LED grow light fixtures suspended from ceiling",
        "title": "Commercial Cannabis Growing Room With Foldable LED Grow Lights",
        "caption": "Large-scale commercial cannabis growing room with dense plant canopy under multiple multi-bar foldable LED grow light fixtures and HVAC ductwork overhead.",
        "description": "Wide-angle view of a commercial cannabis cultivation room with a dense canopy of vegetative cannabis plants in pots filling the entire floor space. Multiple foldable multi-bar LED grow light fixtures hang from the ceiling at uniform height, delivering full-spectrum illumination. Industrial HVAC ductwork and electrical infrastructure are visible along the white walls and ceiling.",
    },
    37445: {
        "alt_text": "Close-up of LED grow light bar showing white and red SMD diode chips on aluminum PCB board",
        "title": "LED Grow Light Bar Diode Detail — Full-Spectrum White and Red Chips",
        "caption": "Close-up of an LED grow light bar PCB showing rows of white and deep-red SMD diode chips mounted on an aluminum heat-dissipating substrate.",
        "description": "Macro close-up of an LED grow light bar showing the diode array in detail. Rows of warm-white and cool-white SMD LED chips are interspersed with smaller deep-red supplemental diodes, all surface-mounted on an aluminum PCB with black anodized heatsink housing. This full-spectrum diode configuration delivers photosynthetically optimized light for horticultural applications.",
    },
    37444: {
        "alt_text": "LED grow light driver unit with aluminum heatsink housing alongside disassembled LED bar fixture sections and waterproof connector",
        "title": "LED Grow Light Driver and Bar Fixture Components",
        "caption": "LED grow light components: aluminum-body driver/power supply unit with finned heatsink, linear LED bar sections, and multi-pin waterproof connector cable.",
        "description": "Studio product photo showing disassembled LED grow light components on a gray background. The aluminum driver unit features a finned heatsink housing for thermal management, connected via a multi-pin waterproof connector cable to linear LED bar fixture sections. This modular design allows field serviceability and component-level replacement in commercial grow light installations.",
    },
    # ═══ Cannabis page ═══
    37356: {
        "alt_text": "Cannabis mother plants in black fabric pots on wheeled platforms under overhead linear LED bar grow lights",
        "title": "Cannabis Mother Plant Room With LED Bar Grow Lights",
        "caption": "Cannabis mother plant maintenance room with mature stock plants in black fabric pots on wheeled platforms, illuminated by staggered linear LED bar grow lights.",
        "description": "Interior of a cannabis mother plant room used to maintain genetic stock for cloning operations. Mature cannabis mother plants grow in black fabric pots placed on individual wheeled platforms for easy repositioning. Overhead linear LED bar grow lights are arranged in a staggered pattern to provide uniform canopy coverage during the extended vegetative photoperiod required for mother plant maintenance.",
    },
    37345: {
        "alt_text": "Two tiers of vertical farming shelf with green and red lettuce varieties growing under LED bar lights",
        "title": "Vertical Farming Shelf Detail — Green and Red Lettuce Under LED Lighting",
        "caption": "Close-up of two vertical farming shelf tiers growing green butterhead and red oak leaf lettuce varieties under linear LED bar grow lights.",
        "description": "Detail view of two growing tiers on a vertical farming shelf system. The upper tier holds mature green butterhead lettuce heads, while the lower tier displays a mix of green and deep-red or purple oak leaf lettuce varieties in growing trays. LED bar grow lights mounted above each tier provide targeted illumination for each crop level independently.",
    },
    37344: {
        "alt_text": "Cannabis clone propagation tray with young rooted cuttings in rockwool cubes under LED bar grow lights",
        "title": "Cannabis Clone Propagation Tray Under LED Grow Lights",
        "caption": "Cannabis clone propagation tray holding rows of young rooted cuttings in rockwool starter cubes, illuminated by overhead linear LED bar grow lights in a sterile propagation room.",
        "description": "Cannabis clone propagation tray in a clean commercial nursery room. Rows of young cannabis cuttings are rooted in rockwool starter cubes inside a standard 10x20 propagation tray. Overhead linear LED bar grow lights provide the moderate light intensity (100-250 umol/m2/s) optimal for root development during the cloning stage. The sterile white room environment minimizes pathogen risk during this vulnerable growth phase.",
    },
    37343: {
        "alt_text": "Commercial glass greenhouse with tomato rows and LED interlighting fixtures positioned between crop canopy levels",
        "title": "Greenhouse Tomato Cultivation With LED Interlighting",
        "caption": "Commercial greenhouse tomato production with LED interlighting fixtures installed between vine-trained crop rows to supplement lower-canopy photosynthesis.",
        "description": "Interior of a commercial glass greenhouse showing long rows of vine-trained tomato plants with clusters of ripe red fruit. LED interlighting fixtures are positioned at mid-canopy height between the crop rows, supplementing natural sunlight to drive photosynthesis in lower leaf layers that would otherwise be shaded by the upper canopy. This interlighting strategy increases fruit yield per square meter in high-wire tomato production systems.",
    },
    37342: {
        "alt_text": "Wide-angle view of a large commercial glass greenhouse with tomato crop rows and overhead supplemental lighting under blue sky",
        "title": "Commercial Glass Greenhouse Interior — Tomato Production at Scale",
        "caption": "Wide-angle perspective down a long commercial glass greenhouse with tomato crop rows extending toward the horizon under overhead supplemental lighting.",
        "description": "Panoramic interior view of a large-scale commercial glass greenhouse dedicated to tomato production. Long parallel rows of vine-trained tomato plants stretch into the distance on both sides of a central walkway. Overhead supplemental lighting fixtures augment natural daylight entering through the glass roof. The blue sky visible through the glazing indicates daytime operation with supplemental lighting boosting daily light integral during low-light periods.",
    },
    37338: {
        "alt_text": "Cannabis vegetative growth room with plants in fabric pots on rolling benches under overhead LED bar grow lights",
        "title": "Cannabis Vegetative Room With Rolling Benches and LED Bar Lighting",
        "caption": "Cannabis vegetative growth room with plants in black fabric pots arranged on commercial rolling benches, illuminated by rows of overhead linear LED bar grow lights.",
        "description": "Interior of a commercial cannabis vegetative growth room. Cannabis plants in black fabric pots are arranged on rolling bench systems that maximize floor space utilization. Overhead rows of linear LED bar grow lights deliver the 18-hour photoperiod required during vegetative growth. The rolling bench design allows growers to open aisles between any two benches for plant access while maintaining dense canopy coverage.",
    },
    37337: {
        "alt_text": "LED grow light PCB board with labeled multi-channel diode groups at 3000K, 3500K, 5000K, Far Red 730nm, and UV-A 385nm",
        "title": "Multi-Channel LED Spectrum Board — 3000K to UV-A Diode Layout",
        "caption": "LED grow light PCB board showing five labeled diode channels: 3000K warm white, 3500K neutral, 5000K cool white, Far Red 730nm, and UV-A 385nm for full-spectrum tunability.",
        "description": "Close-up of a multi-channel LED grow light PCB board with clearly labeled diode groups. Five spectral channels are visible: 3000K warm white, 3500K neutral white, 5000K cool white, Far Red 730nm (for Emerson enhancement and flowering initiation), and UV-A 385nm (for trichome development and pathogen suppression). This multi-channel architecture enables independent spectrum tuning across growth stages from propagation through flowering.",
    },
    37336: {
        "alt_text": "Large commercial cannabis grow room with multiple rows of plants on rolling benches under overhead LED bar grow lights",
        "title": "Commercial Cannabis Grow Room Layout — Rolling Benches With LED Lighting",
        "caption": "Wide-angle view of a commercial cannabis grow room with multiple plant rows on rolling benches under a grid of overhead LED bar grow lights.",
        "description": "Elevated wide-angle view of a large commercial cannabis grow room. Multiple rows of cannabis plants in black pots are arranged on commercial rolling bench systems. A uniform grid of overhead linear LED bar grow lights covers the entire canopy area. The white walls and ceiling maximize light reflection, while visible HVAC infrastructure maintains the precise temperature and humidity control required for commercial cannabis production.",
    },
    37335: {
        "alt_text": "Commercial cannabis flowering room with rows of mature budding plants under pink-spectrum LED grow lights",
        "title": "Cannabis Flowering Room Under Pink-Spectrum LED Grow Lights",
        "caption": "Commercial cannabis flowering room with two long rows of mature budding plants illuminated by pink-spectrum LED grow lights optimized for the 12/12 flowering photoperiod.",
        "description": "Dramatic interior view of a commercial cannabis flowering room. Two long rows of mature cannabis plants in full flower stage line a central aisle. The pink-spectrum LED grow lights overhead deliver a red-heavy spectral output optimized for flowering and resin production during the 12/12 photoperiod. The warm pink glow is characteristic of LED fixtures with enhanced deep-red (660nm) and far-red (730nm) diode ratios for reproductive growth.",
    },
    37334: {
        "alt_text": "Macro close-up of mature cannabis flower bud showing purple coloring and visible trichome frost on sugar leaves",
        "title": "Cannabis Flower Bud Macro — Trichome Development and Purple Phenotype",
        "caption": "Macro close-up of a mature cannabis flower bud displaying dense trichome frost on sugar leaves and deep purple anthocyanin coloring in the calyxes.",
        "description": "Extreme macro photograph of a mature cannabis flower bud at peak harvest readiness. Dense milky-white trichome heads coat the sugar leaves and calyxes, indicating optimal cannabinoid and terpene development. Deep purple anthocyanin pigmentation in the inner calyxes suggests genetic expression enhanced by controlled temperature differentials during the final flowering weeks under LED grow light cultivation.",
    },
    37333: {
        "alt_text": "Commercial cannabis cultivation room with two rows of mature plants in fabric pots under foldable multi-bar LED grow lights",
        "title": "Commercial Cannabis Room With Foldable Multi-Bar LED Grow Lights",
        "caption": "Commercial cannabis cultivation room showing two rows of mature plants in black fabric pots on rolling benches under grid-mounted foldable multi-bar LED grow light fixtures.",
        "description": "Interior of a commercial cannabis cultivation room viewed from one end looking down the center aisle. Two rows of mature cannabis plants in black fabric pots stand on rolling benches. Multiple foldable multi-bar LED grow light fixtures are suspended from the ceiling in a grid pattern, delivering uniform PPFD across the entire canopy. White walls and clean polished concrete floor reflect the professional cultivation environment.",
    },
    # ═══ 4x4 Grow Light Article ═══
    37330: {
        "alt_text": "Foldable LED grow light disassembled flatlay showing LED bar panels, X-shaped spider mount, aluminum driver, and power cables",
        "title": "Foldable LED Grow Light Components — Disassembled Flatlay View",
        "caption": "Flatlay of a foldable LED grow light disassembled into its core components: LED bar panels in two sizes, X-shaped spider mount frame, aluminum driver unit, and power cables.",
        "description": "Bird-eye flatlay product photo of a foldable LED grow light fully disassembled on a gray background. Visible components include two sizes of LED bar panels, an X-shaped aluminum spider mount that serves as the folding frame, a separate aluminum-body driver unit, and power cables with waterproof connectors. This modular design enables tool-free assembly, compact shipping, and field-serviceable component replacement.",
    },
    37329: {
        "alt_text": "4x4 grow tent setup with LED grow light, carbon filter, and ducting installed inside reflective mylar-lined tent",
        "title": "Complete 4x4 Grow Tent Setup With LED Light and Ventilation",
        "caption": "Fully assembled 4x4 grow tent with LED grow light, inline carbon filter, flexible ducting, and clip fan inside a mylar-reflective interior.",
        "description": "Interior view of a fully assembled 4x4 grow tent for home cultivation. A foldable LED grow light hangs from the top center, illuminating the reflective mylar-lined interior. Above the light, a carbon filter connects to flexible aluminum ducting for odor scrubbing and air exchange. This compact self-contained setup provides controlled-environment growing in a standard residential room.",
    },
    37328: {
        "alt_text": "Side-by-side comparison of a small home grow tent setup and an open-room commercial grow station with LED overhead lighting",
        "title": "Home Grow Tent vs Commercial Open-Room Growing Station Comparison",
        "caption": "Split comparison: compact home grow tent with reflective lining (left) versus open-room commercial growing station with overhead LED grow light and rolling table (right).",
        "description": "Side-by-side comparison image showing two LED grow light deployment scales. Left: a compact home grow tent in a garage setting with mylar reflective lining and small LED fixture. Right: an open-room commercial growing station with a large foldable LED grow light suspended over a cannabis canopy on a rolling stainless-steel table. This comparison illustrates how the same LED technology scales from home hobby to commercial production environments.",
    },
    37327: {
        "alt_text": "Clean grow room with foldable LED grow light suspended over cannabis seedling tray on rolling metal table",
        "title": "4x4 Grow Room Setup — Foldable LED Light Over Seedling Tray",
        "caption": "Minimalist 4x4 grow room with a foldable multi-bar LED grow light suspended above a cannabis seedling tray on a rolling stainless-steel table.",
        "description": "Clean commercial-style 4x4 grow room with white walls and polished floor. A foldable multi-bar LED grow light hangs from ceiling cables above a dense tray of cannabis seedlings on a rolling stainless-steel table. A wall-mounted AC unit provides climate control. This setup represents the recommended single-light 4x4 cell configuration for clone-to-veg transition growing.",
    },
    # ═══ 100W LED Article ═══
    37322: {
        "alt_text": "Five compact LED grow light fixtures in different form factors displayed on gray pedestals for size comparison",
        "title": "100W LED Grow Light Fixture Lineup — Five Form Factor Comparison",
        "caption": "Five 100W-class LED grow light fixtures in different form factors — flat panel, compact bar, flood module, quantum board, and single-bar — displayed on pedestals for direct size comparison.",
        "description": "Product lineup photo showing five different 100W-class LED grow light fixtures displayed on gray cubic pedestals against a neutral background. The fixtures represent the main form factors available in this wattage class: flat panel, compact multi-bar, flood-style module, quantum board, and single linear bar. This side-by-side display enables direct visual comparison of size, profile, and build quality across competing designs.",
    },
    37321: {
        "alt_text": "Cannabis plants in fabric pots growing along a wall-mounted shelf under a single overhead LED bar grow light with clip fan",
        "title": "Small-Space Cannabis Growing Under 100W LED Bar Light",
        "caption": "Cannabis plants in black fabric pots on a wall-mounted metal shelf rail, illuminated by a single overhead linear LED bar grow light in a small indoor space.",
        "description": "Small-space indoor cannabis growing setup. Several cannabis plants in black fabric pots are arranged along a wall-mounted metal shelf rail. A single overhead linear LED bar grow light provides illumination, while a clip-on oscillating fan maintains air circulation. This compact linear layout demonstrates how a 100W-class LED bar can serve a narrow single-row growing arrangement in limited spaces.",
    },
    37320: {
        "alt_text": "Two cannabis plants in fabric pots under a flat-panel LED grow light inside a reflective growing space with bamboo stakes",
        "title": "Cannabis Vegetative Growth Under 100W Flat-Panel LED Grow Light",
        "caption": "Two cannabis plants with bamboo training stakes growing in fabric pots under a flat-panel LED grow light inside a reflective indoor growing space.",
        "description": "Two cannabis plants in black fabric pots grow inside a reflective-walled indoor space. Bamboo stakes provide structural support for the training canopy. A flat-panel LED grow light hangs directly above at close distance, and a digital environmental monitor is visible on a nearby shelf. This setup demonstrates a typical 100W flat-panel LED deployment for small-scale vegetative cannabis growing with limited vertical clearance.",
    },
    37319: {
        "alt_text": "Multi-tier nursery shelving with cannabis seedling trays in humidity domes under 100W LED grow lights on each level",
        "title": "Cannabis Nursery Room — Multi-Tier Propagation Under 100W LED Lights",
        "caption": "Multi-tier commercial nursery shelving with cannabis seedling trays in humidity domes, each tier lit by a compact 100W LED grow light for early-stage propagation.",
        "description": "Commercial cannabis nursery room with multi-tier metal shelving. Each shelf holds propagation trays with cannabis seedlings under clear humidity domes. Compact 100W-class LED grow lights are mounted above each tier, delivering the moderate light intensity (100-250 umol/m2/s) optimal for early-stage root development and seedling establishment. A stainless-steel utility cart stands nearby for nursery workflow.",
    },
    # ═══ OEM/ODM ═══
    37233: {
        "alt_text": "Foldable LED grow light fixtures in two sizes displayed with brown shipping cartons for OEM packaging presentation",
        "title": "Project Charlie OEM LED Grow Light Fixtures With Shipping Packaging",
        "caption": "Two foldable LED grow light fixtures in different sizes displayed alongside branded shipping cartons, showing Project Charlie OEM packaging and product range.",
        "description": "OEM product presentation showing two foldable LED grow light fixtures in different wattage sizes displayed with their brown corrugated shipping cartons on a dark background. One fixture is fully unfolded showing the multi-bar LED array, while the other is partially folded for compact packaging. This presentation showcases Project Charlie OEM manufacturing capabilities and product-ready packaging for private-label and white-label distribution partners.",
    },
    37232: {
        "alt_text": "LED grow light OEM component flatlay showing Meanwell driver, LED PCB boards, aluminum heatsink profiles, connectors, and cables",
        "title": "LED Grow Light OEM Component Kit — Driver, PCBs, Heatsinks, and Wiring",
        "caption": "Flatlay of LED grow light OEM components: Meanwell power driver, LED PCB boards with diode arrays, aluminum heatsink extrusion profiles, waterproof connectors, and daisy-chain cables.",
        "description": "Technical flatlay of LED grow light OEM component kit on a dark background. Components include a Meanwell constant-current power driver, multiple LED PCB boards with pre-soldered diode arrays, aluminum heatsink extrusion profiles for thermal management, waterproof multi-pin connectors, daisy-chain power cables, and mounting hardware. This kit represents the building blocks available to ODM partners for custom LED grow light assembly and private-label manufacturing.",
    },
    # ═══ S05-SZ48-800 Product ═══
    37116: {
        "alt_text": "Project Charlie S05 SZ48 800W foldable LED grow light three-quarter angle view showing 8-bar design and center driver housing",
        "title": "Project Charlie S05 SZ48 800W LED Grow Light — Three-Quarter Angle View",
        "caption": "Project Charlie S05 SZ48 800W foldable LED grow light shown at three-quarter angle, displaying the 8-bar LED array and center-mounted aluminum driver housing.",
        "description": "Studio product photo of the Project Charlie S05 SZ48 800W foldable LED grow light at three-quarter angle on a white background. The fixture features eight parallel LED bars with full-spectrum Samsung diodes, connected to a center-mounted aluminum driver housing. The foldable design enables compact packaging and tool-free deployment for commercial cannabis cultivation and vertical farming applications.",
    },
    37117: {
        "alt_text": "Close-up of Project Charlie S05 SZ48 800W LED bars showing Samsung diode chips with model label visible on aluminum PCB",
        "title": "Project Charlie S05 SZ48 800W LED Bar Diode Detail With Samsung Chips",
        "caption": "Close-up of Project Charlie S05 SZ48 800W LED bars showing white and red Samsung SMD diodes on aluminum PCB with printed model identification.",
        "description": "Detail close-up of LED bars on the Project Charlie S05 SZ48 800W grow light fixture. White and red Samsung SMD diode chips are surface-mounted on aluminum PCB strips. The printed label project-charlie S05-SZ48-800 is visible on the bar edge. Waterproof push-fit connectors enable tool-free bar replacement. The red supplemental diodes boost the 660nm deep-red wavelength critical for flowering-stage photomorphogenesis.",
    },
    37118: {
        "alt_text": "Commercial vertical farming facility aisle with multi-tier racks of leafy greens and microgreens under LED bar grow lights",
        "title": "Vertical Farming Facility — Multi-Tier Racks With LED Grow Lights",
        "caption": "Perspective view down a commercial vertical farming facility aisle with multi-tier racks of leafy greens and microgreens illuminated by LED bar grow lights on every tier.",
        "description": "Perspective view down a long aisle in a commercial vertical farming facility. Multi-tier metal racks on both sides hold trays of leafy greens, herbs, and microgreens at various growth stages. LED bar grow lights are mounted above each tier, creating a stacked illumination grid that maximizes growing volume per square foot of floor space. The clean white facility with polished floors represents a modern controlled-environment agriculture installation.",
    },
    37119: {
        "alt_text": "Project Charlie S05 SZ48 800W LED grow light construction detail collage showing hanging mount, hinge joint, LED diodes, and cable connectors",
        "title": "Project Charlie S05 SZ48 800W Construction Details — Four-Panel Collage",
        "caption": "Four-panel construction detail collage of the Project Charlie S05 SZ48 800W: carabiner hanging mount, aluminum frame hinge joint, LED bar diode close-up, and waterproof cable connectors.",
        "description": "Four-panel technical detail collage of the Project Charlie S05 SZ48 800W LED grow light. Top-left: stainless-steel carabiner hanging mount for adjustable suspension. Top-right: aluminum frame hinge joint enabling the foldable design. Bottom-left: LED bar close-up showing full-spectrum diode array. Bottom-right: waterproof cable connectors and driver housing for daisy-chain power distribution. These details highlight the commercial-grade build quality and field-serviceable modular construction.",
    },
    37120: {
        "alt_text": "Project Charlie S05 SZ48 800W LED grow light suspended over lettuce plants in a clean white indoor growing setup",
        "title": "Project Charlie S05 SZ48 800W LED Grow Light — Indoor Lettuce Application",
        "caption": "Project Charlie S05 SZ48 800W foldable LED grow light suspended over a tray of lettuce plants in a clean white indoor growing environment.",
        "description": "Application photo showing the Project Charlie S05 SZ48 800W foldable LED grow light suspended from ceiling cables over a white tray of mature lettuce plants. The clean white background highlights the fixture profile and light distribution pattern. This setup demonstrates the fixture versatility for controlled-environment leafy green production beyond its primary commercial cannabis application.",
    },
    37121: {
        "alt_text": "Project Charlie S05 SZ48 800W foldable LED grow light front view on white background showing 8-bar array with Samsung diodes",
        "title": "Project Charlie S05 SZ48 800W LED Grow Light — Front Studio View",
        "caption": "Project Charlie S05 SZ48 800W foldable LED grow light front view displaying eight LED bars with Samsung diodes and center driver unit on white background.",
        "description": "Front studio product photo of the Project Charlie S05 SZ48 800W foldable LED grow light on a white background. Eight parallel LED bars with Samsung full-spectrum diodes are arranged symmetrically around a center-mounted aluminum driver unit. The warm-tone diode pattern is visible across all bars. This 800W fixture delivers approximately 2080 umol/s PPF for commercial 4x4 to 5x5 flowering coverage.",
    },
    # ═══ S01-SS46-600 Product ═══
    37140: {
        "alt_text": "Project Charlie S01 SS46 600W foldable LED grow light front view on white background showing 8-bar design and driver cable",
        "title": "Project Charlie S01 SS46 600W LED Grow Light — Front Reference View",
        "caption": "Project Charlie S01 SS46 600W foldable LED grow light front view with eight LED bars and center driver unit on white background.",
        "description": "Reference product photo of the Project Charlie S01 SS46 600W foldable LED grow light on a white background. Eight parallel LED bars with full-spectrum diodes span the frame, connected to a center-mounted gray driver housing with a single power cable. This 600W fixture is designed for 4x4 flowering coverage, delivering approximately 1560 umol/s PPF at wall for commercial cannabis and controlled-environment agriculture.",
    },
    37141: {
        "alt_text": "Close-up of Project Charlie S01 SS46 600W LED bars showing white and red SMD diodes on aluminum PCB with frame screws",
        "title": "Project Charlie S01 SS46 600W LED Bar Diode Close-Up",
        "caption": "Close-up of two parallel LED bars on the Project Charlie S01 SS46 600W showing full-spectrum white and deep-red SMD diode chips on brushed aluminum PCB.",
        "description": "Macro close-up of two parallel LED bars on the Project Charlie S01 SS46 600W grow light fixture. Full-spectrum white SMD diodes and supplemental deep-red chips are mounted on brushed aluminum PCB strips. Phillips-head frame screws and the aluminum heatsink profile are visible, demonstrating the fixture build quality and thermal management design for sustained commercial operation.",
    },
    37152: {
        "alt_text": "Project Charlie S01 SS46 600W foldable LED grow light three-quarter angle view showing 8-bar layout and driver housing",
        "title": "Project Charlie S01 SS46 600W LED Grow Light — Three-Quarter Angle View",
        "caption": "Project Charlie S01 SS46 600W foldable LED grow light at three-quarter angle displaying eight LED bars and center gray driver housing.",
        "description": "Studio product photo of the Project Charlie S01 SS46 600W foldable LED grow light at three-quarter angle on a white background. The eight-bar LED array and center-mounted gray driver housing are clearly visible from this perspective. The foldable frame design allows the fixture to collapse for compact shipping and storage, then unfold for instant deployment without tools.",
    },
    37153: {
        "alt_text": "Project Charlie S01 SS46 600W foldable LED grow light studio photo on white background showing 8-bar full-spectrum design",
        "title": "Project Charlie S01 SS46 600W LED Grow Light — Studio Hero Shot",
        "caption": "Project Charlie S01 SS46 600W foldable LED grow light hero product photo on white background with eight full-spectrum LED bars.",
        "description": "Hero studio product photo of the Project Charlie S01 SS46 600W foldable LED grow light on a clean white background. Eight parallel LED bars with full-spectrum diode arrays span the aluminum frame, with a center-mounted gray driver housing and hanging eye-hook. This front-facing view is the primary product image used for e-commerce listings, spec sheets, and catalog presentations.",
    },
    37154: {
        "alt_text": "Project Charlie S01 SS46 600W LED grow light suspended over herb plants on a wooden tabletop in a modern home setting",
        "title": "Project Charlie S01 SS46 600W LED Grow Light — Home Indoor Garden Application",
        "caption": "Project Charlie S01 SS46 600W LED grow light suspended above basil, lettuce, and herb trays on a wooden tabletop in a modern home setting with wall art and books.",
        "description": "Lifestyle application photo of the Project Charlie S01 SS46 600W LED grow light in a residential indoor garden setting. The fixture hangs from ceiling cables above three trays of basil, microgreens, and lettuce on a wooden tabletop. Framed wall art, potted plants, and books create a modern home interior context, demonstrating how the commercial-grade fixture integrates into residential indoor gardening beyond its primary commercial use case.",
    },
    37155: {
        "alt_text": "Project Charlie S01 SS46 600W foldable LED grow light detailed front view showing LED bar array and center driver with hanging hook",
        "title": "Project Charlie S01 SS46 600W LED Grow Light — Detailed Front View",
        "caption": "Project Charlie S01 SS46 600W foldable LED grow light detailed front view showing eight LED bars, center driver housing, and top hanging hook.",
        "description": "Detailed front-facing product photo of the Project Charlie S01 SS46 600W foldable LED grow light. The eight-bar LED array, center-mounted driver housing, and top hanging eye-hook are all clearly visible. This angle reveals the diode spacing pattern and bar alignment that determine the fixture PPFD uniformity across its rated 4x4-foot flowering coverage footprint.",
    },
    37156: {
        "alt_text": "Commercial vertical farming facility with multi-tier racks of microgreens and seedlings under LED bar grow lights along a long aisle",
        "title": "Vertical Farming Facility — Microgreens and Seedlings Under LED Grow Lights",
        "caption": "Commercial vertical farming facility with multi-tier metal racks holding microgreen and seedling trays under LED bar grow lights, viewed down a long production aisle.",
        "description": "Perspective view down a production aisle in a commercial vertical farming facility. Multi-tier metal racks on one side hold trays of microgreens and seedlings at various growth stages, each tier illuminated by LED bar grow lights. The clean white room with polished flooring and overhead cable management represents a professional controlled-environment agriculture operation for year-round leafy green and microgreen production.",
    },
}

# ── 19 images that ALREADY have alt_text — only need caption + description ──
CAPTION_DESC_ONLY: dict[int, dict[str, str]] = {
    37470: {
        "caption": "Split view: commercial vertical farming racks with LED lighting (left) and facility electrical panel with digital energy meter reading 7.49 kW real-time power draw (right).",
        "description": "Split-panel image illustrating LED grow light energy economics. Left side shows commercial multi-tier vertical farming racks illuminated by LED bar grow lights over leafy greens. Right side shows the facility electrical panel alongside a digital energy monitoring display reading 7.49 kW real-time power, 98.20 kWh daily consumption, and 2,821.10 kWh monthly total with a bar-graph trend. This image demonstrates the real-time energy monitoring capability critical for calculating LED grow light total cost of ownership and ROI.",
    },
    37467: {
        "caption": "Close-up inside a vertical farming rack tier showing LED bar grow light fixtures with daisy-chain connectors mounted 8 inches above baby lettuce canopy.",
        "description": "Detail view inside a vertical farming rack tier. Linear LED bar grow light fixtures with waterproof push-fit daisy-chain connectors are mounted approximately 8 inches above a dense baby lettuce canopy. The close mounting distance and bar spacing demonstrate the tight Z-axis clearance engineering required in multi-tier vertical farms to maximize usable growing volume while maintaining uniform PPFD distribution.",
    },
    37463: {
        "caption": "Four LED grow light form factors for vertical farming compared side by side: single linear bar, multi-bar foldable fixture, flat quantum board panel, and integrated shelf module.",
        "description": "Product comparison flatlay showing four distinct LED grow light form factors laid on a gray surface. From left: a single linear bar fixture, a compact multi-bar foldable unit, a flat quantum board panel, and a larger modular fixture. This side-by-side comparison helps growers evaluate size, profile, and mounting compatibility when selecting LED grow lights for different vertical farming rack configurations and tier clearances.",
    },
    37461: {
        "caption": "Commercial vertical farming racks with five tiers of leafy greens illuminated by LED bar grow lights, perspective view down a warehouse-scale production aisle.",
        "description": "Perspective view down the main aisle of a warehouse-scale vertical farming facility. Multi-tier growing racks extend along one side, each holding five levels of leafy greens illuminated by linear LED bar grow lights. The polished concrete floor and high-bay ceiling lights indicate a professional controlled-environment agriculture installation operating at commercial production scale.",
    },
    37269: {
        "caption": "Infographic: Commercial 5x5 Cell Procurement Workflow — 9 steps from spec sheet and DLC QPL verification through PPFD field test, MOQ negotiation, and rebate filing.",
        "description": "Process infographic titled Commercial 5x5 Cell Procurement Workflow — 9 Steps from Spec to Rebate. Three phases are mapped: Phase A (Spec and Qualify) covers spec sheet review, DLC QPL verification, and RFP issuance. Phase B (Validate and Negotiate) covers sample fixture evaluation, PPFD field testing, and MOQ negotiation. Phase C (Contract, Logistics and Rebate) covers PO/PO terms, freight and dock logistics, and acceptance plus rebate filing. Each step includes a brief description and icon.",
    },
    37268: {
        "caption": "Floor plan infographic showing 10, 25, and 50 commercial 5x5 cell facility layouts with canopy area, total LED wattage, BTU sensible load, and required HVAC tonnage for each scale.",
        "description": "Technical infographic titled Multi-Cell 5x5 Facility Scaling — 10/25/50 Commercial Cells with HVAC Tonnage. Three facility floor plans show progressive scaling from 10 cells (250 sqft canopy, ~10,000W LED, 3 tons AC) through 25 cells (625 sqft, ~25,000W, 7.1 tons) to 50 cells (1,250 sqft, ~50,000W, 14.2 tons). Each layout includes cell grid dimensions, supply ductwork routing, and electrical room placement, helping commercial growers plan facility buildout with accurate HVAC sizing.",
    },
    37267: {
        "caption": "PPFD heatmap for a 5x5-foot grow light footprint at 1000W and 20-inch hang height, showing center-peak distribution from 400 to 1,150 umol/m2/s with color-coded intensity zones.",
        "description": "Top-down PPFD distribution heatmap titled PPFD Distribution — 5x5 Footprint, 1000W Single Fixture, 20-in Hang Height. The color gradient from green (400 umol/m2/s at edges) through yellow to red (1,150 umol/m2/s at center) visualizes the light intensity distribution across a 25-square-foot canopy footprint. This heatmap helps growers evaluate coverage uniformity and identify whether a single 1000W fixture delivers acceptable min/avg uniformity for flowering-stage cannabis across a full 5x5 cell.",
    },
    37266: {
        "caption": "Commercial cannabis flowering room with rows of 5x5 cultivation cells under purple-pink LED grow lights, showing the facility-scale deployment of best 5x5 grow light fixtures.",
        "description": "Dramatic interior view of a commercial cannabis flowering room equipped with best-in-class 5x5 grow light fixtures. Long rows of raised benches hold flowering cannabis plants arranged in 5x5-foot cultivation cells. Purple-pink LED spectrum light fills the room, with HVAC ductwork running along the ceiling for environmental control. The central aisle provides worker access for canopy management during the 12/12 flowering photoperiod.",
    },
    37283: {
        "caption": "PPFD heatmap for a 2x2-foot flowering-stage grow light footprint across 4 sqft, showing 630-850 umol/m2/s distribution with 0.79 min/avg uniformity ratio.",
        "description": "PPFD distribution heatmap titled Flowering-Stage PPFD Distribution — 2x2 Footprint (4 sq ft). The 3x3 measurement grid shows intensity values ranging from 630 umol/m2/s at corners to 850 umol/m2/s at center, with a min/avg uniformity ratio of 0.79 (above the 0.75 target). Color coding from green (low) through yellow to red (high) visualizes the distribution. This heatmap validates that a properly sized 2x2 grow light delivers acceptable flowering-stage PPFD uniformity.",
    },
    37282: {
        "caption": "Educational diagram defining a 2x2 grow light footprint: 24 x 24 inches (4 sqft / 0.37 sqm) with PPFD targets for clone/seedling (100-250), veg (300-500), and flower (600-900) umol/m2/s.",
        "description": "Educational infographic titled What Is a 2x2 Grow Light. A labeled 24x24-inch (2x2 ft) square overlay on a cannabis canopy background defines the footprint dimensions (4 sqft = 0.37 sqm). Three color-coded PPFD target bands are shown: clone/seedling at 100-250 umol/m2/s, vegetative at 300-500, and flowering at 600-900. Published by Project Charlie, this diagram establishes the baseline PPFD expectations for growers shopping for a 2x2 coverage grow light.",
    },
    37277: {
        "caption": "PPFD heatmap for a 2x2 tent footprint with a 250W LED at 16-inch hang height, showing 612-945 umol/m2/s distribution with 0.78 min/avg uniformity.",
        "description": "PPFD distribution heatmap titled PPFD Distribution — 2x2 Tent Footprint, 250W Single Fixture, 16-in Hang Height. The 3x3 measurement grid reveals values from 612 umol/m2/s at the corners to a 945 umol/m2/s center peak, with min/avg uniformity of 0.78. The color gradient from green to deep red helps growers visualize hot spots and edge falloff, validating that a 250W fixture can deliver flowering-adequate PPFD across a 2x2-foot tent footprint.",
    },
    37276: {
        "caption": "Small 2x2 grow tent housing a cannabis mother plant on the upper tier and clone seedling tray below, illuminated by purple-pink LED grow light spectrum.",
        "description": "Interior of a compact 2x2 grow tent setup for mother plant maintenance and clone propagation. The upper tier holds a single cannabis mother plant in a fabric pot, while the lower shelf houses a seedling/clone tray. Purple-pink LED spectrum lighting optimized for vegetative growth fills the mylar-reflective interior. This dual-tier 2x2 configuration maximizes the small footprint by combining mother maintenance and clone rooting in one tent.",
    },
    37273: {
        "caption": "PPFD heatmap for a 5x5 tent footprint with a 700W LED at 20-inch hang height, showing 410-870 umol/m2/s distribution with 0.72 min/avg uniformity.",
        "description": "PPFD distribution heatmap titled PPFD Distribution — 5x5 Tent Footprint, 700W Single Fixture, 20-in Hang Height. The measurement grid shows values from 410 umol/m2/s at far corners to 870 umol/m2/s at center, with min/avg uniformity of 0.72 (below the 0.75 target, noted in the annotation). Color coding from green to red visualizes the center-heavy distribution, indicating that a 700W fixture in a 5x5 tent produces moderate edge falloff that growers should compensate for with reflective walls or supplemental side lighting.",
    },
    37272: {
        "caption": "Home 5x5 grow tent with a single flowering cannabis plant under an LED grow light at 20-inch hang height, clip fan mounted on a tent pole.",
        "description": "Interior of a home 5x5 grow tent placed in a residential room. A single cannabis plant in mid-flower stage grows in a fabric pot under a foldable LED grow light suspended at approximately 20-inch hang height. A clip fan mounted on a tent pole provides air circulation. The mylar-reflective interior walls maximize light efficiency. This setup represents a typical home grower 5x5 tent configuration for single-plant or small-canopy flowering.",
    },
    37251: {
        "caption": "Residential closet converted to a single-plant grow cabinet with a compact 200W LED grow lamp, carbon filter, and clip fan inside reflective lining.",
        "description": "A residential closet retrofitted as a single-plant grow cabinet. A healthy foliage plant grows in a black fabric pot on a wooden stool under a compact 200W LED grow lamp. Inside the reflective mylar-lined closet, a carbon filter/fan combo handles air filtration. The setup is viewed through the open door from the adjoining living room, demonstrating how a standard residential closet can be converted into a functional micro-grow space with a 200W LED light.",
    },
    37249: {
        "caption": "Four-panel crop application grid for a 200W LED grow lamp: microgreens tray (top-left), succulents and cacti (top-right), orchids (bottom-left), and trailing foliage houseplant (bottom-right).",
        "description": "Four-panel overhead flatlay showing four different crop applications for a compact 200W LED grow lamp. Top-left: a dense microgreen tray under a clip-mount LED. Top-right: a collection of succulents and a cactus under a gooseneck LED desk lamp. Bottom-left: flowering orchids under a small LED panel. Bottom-right: a trailing pothos houseplant under an adjustable LED floor lamp. This multi-use grid demonstrates the versatility of 200W-class LED grow lamps beyond cannabis for ornamental and edible home gardening.",
    },
    37248: {
        "caption": "Four grow tents in progressively larger sizes (2x2, 3x3, 2x4, 4x4) displayed on a countertop, each with LED grow light visible inside the open front.",
        "description": "Product comparison photo showing four grow tents in progressively larger sizes arranged left to right on a gray countertop against a dark background. Each tent is open at the front, revealing the reflective mylar interior and LED grow light installed inside. The size progression from approximately 2x2 to 4x4 feet helps buyers visualize tent scale relative to their available space and choose the correct 200W-class LED fixture for their footprint.",
    },
    37247: {
        "caption": "Compact 200W LED grow lamp on an adjustable desk-lamp stand illuminating a Monstera houseplant on a modern kitchen countertop.",
        "description": "Lifestyle product photo of a compact 200W LED grow lamp in a modern kitchen setting. The lamp sits on an adjustable weighted desk-lamp stand next to a healthy Monstera deliciosa in a terracotta pot on a wooden kitchen counter. Natural daylight from a nearby window supplements the LED light. Books, wooden cutting boards, and kitchen shelving complete the domestic scene, positioning the 200W LED grow lamp as an interior-friendly supplement for houseplant care.",
    },
    37246: {
        "caption": "3x3 grow tent in a home garage with a cannabis canopy in vegetative stage under a 200W LED grow light, carbon filter and ducting installed at top.",
        "description": "A 3x3-foot grow tent set up in a residential garage. Inside, a vegetative cannabis canopy fills the tent floor under a 200W-class LED grow light suspended from the top frame. A carbon filter and flexible ducting are installed at the tent ceiling for odor control and air exchange. Tools and a workbench visible in the garage background place this setup in a typical home-grower environment.",
    },
}


def _safe(text: str) -> str:
    return text.replace("'", "’")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    all_patches: list[tuple[int, dict[str, str]]] = []

    for mid, meta in FULL_META.items():
        payload: dict[str, str] = {}
        for k in ("alt_text", "title", "caption", "description"):
            if k in meta and meta[k]:
                payload[k] = _safe(meta[k])
        all_patches.append((mid, payload))

    for mid, meta in CAPTION_DESC_ONLY.items():
        payload = {}
        for k in ("caption", "description"):
            if k in meta and meta[k]:
                payload[k] = _safe(meta[k])
        all_patches.append((mid, payload))

    print(f"Total patches: {len(all_patches)}")
    print(f"  Full (alt+title+caption+desc): {len(FULL_META)}")
    print(f"  Caption+desc only: {len(CAPTION_DESC_ONLY)}")

    if args.dry_run:
        for mid, payload in all_patches[:5]:
            print(f"\n  ID={mid}")
            for k, v in payload.items():
                print(f"    {k}: {v[:90]}...")
        print(f"\n  ... and {len(all_patches) - 5} more")
        return

    ok = 0
    fail = 0
    with httpx.Client(auth=AUTH, headers=CF) as c:
        for i, (mid, payload) in enumerate(all_patches, 1):
            r = c.post(f"{WP_BASE}/media/{mid}", json=payload, timeout=30)
            if r.status_code == 200:
                ok += 1
            elif r.status_code == 403:
                cleaned = {k: v.replace("'", "").replace("’", "") for k, v in payload.items()}
                r2 = c.post(f"{WP_BASE}/media/{mid}", json=cleaned, timeout=30)
                if r2.status_code == 200:
                    ok += 1
                else:
                    fail += 1
                    print(f"  FAIL ID={mid}: HTTP {r2.status_code}", file=sys.stderr)
            else:
                fail += 1
                print(f"  FAIL ID={mid}: HTTP {r.status_code} {r.text[:200]}", file=sys.stderr)

            if i % 10 == 0 or i == len(all_patches):
                print(f"  Progress: {i}/{len(all_patches)} — ok={ok}, fail={fail}")
            time.sleep(0.5)

    print(f"\nDone: {ok} updated, {fail} failed out of {len(all_patches)} total")


if __name__ == "__main__":
    main()
